### ISSUE TITLE
Hide image data and other additional features from Zanka Wired Clients

### ISSUE THREAD

**Issue by docmeth02** [emily-elizabeth/Swirl#2]
Can we please go back to the way sWired used to send images?

SAY 1 chr(128) + "<img src="%s"/>" + EOT

That way the legacy clients will not display all the base64 data in chat :)

**Comment by emily-elizabeth** [comment]
Your telegram bot doesn't seem to like it, but it has been completed
There is a single byte (128) added to the beginning of the chat
